### ISSUE TITLE
Trying to get the samples in the readme to work

### ISSUE THREAD

**Issue by NikkyAI** [lightningkite/koolui#2]
I started by copying the sample code in the README.md for javafx, but apparently there must have been some changes to the api

the immidate error is 

```
Error:(25, 58) Kotlin: Type mismatch: inferred type is MainVG<Node> but Node was expected
```

in

```
primaryStage.scene = Scene(Factory().contentRoot(mainVg) as Parent)
```

I also noticed that the maven artifacts are quite a it older than the last activity on the repository

another thing: maybe its impossible.. but it would be nice to add the transitive dependency for reacktive automatically

**Comment by UnknownJoe796** [comment]
Thanks for the feedback!  I'll get back to this project in about a month, and I'll most certainly get this fixed.  Right now I'm swamped with other stuff.
